JlCompress Class Reference
Static Public Member Functions
static bool compressFile (QString fileCompressed, QString file)
static bool compressFiles (QString fileCompressed, QStringList files)
static bool compressDir (QString fileCompressed, QString dir=QString(), bool recursive=true)
static QString extractFile (QString fileCompressed, QString file, QString fileDest=QString())
static QStringList extractFiles (QString fileCompressed, QStringList files, QString dir=QString())
static QStringList extractDir (QString fileCompressed, QString dir=QString())
static QStringList getFileList (QString fileCompressed)
Member Function Documentation
bool JlCompress::compressFile (QString fileCompressed, QString file) [static]
OK Comprime il file fileName nel file fileCompressed. Se la funzione fallisce restituisce false e cancella il file che si è tentato di creare.
La funzione fallisce se: * non si riesce ad aprire l'oggetto zip; * la compressione del file fallisce; * non si riesce a chiudere l'oggetto zip;
References QuaZip::close(), QuaZip::getZipError(), QuaZip::mdCreate, and QuaZip::open().
bool JlCompress::compressFiles (QString fileCompressed, QStringList files) [static]
OK Comprime i file specificati in files nel file fileCompressed. Se la funzione fallisce restituisce false e cancella il file che si è tentato di creare.
La funzione fallisce se: * non si riesce ad aprire l'oggetto zip; * la compressione di un file fallisce; * non si riesce a chiudere l'oggetto zip;
References QuaZip::close(), QuaZip::getZipError(), QuaZip::mdCreate, and QuaZip::open().
bool JlCompress::compressDir (QString fileCompressed, QString dir = QString(), bool recursive = true) [static]
OK Comprime la cartella dir nel file fileCompressed, se recursive è true allora comprime anche le sotto cartelle. Se la funzione fallisce restituisce false e cancella il file che si è tentato di creare.
La funzione fallisce se: * non si riesce ad aprire l'oggetto zip; * la compressione di un file fallisce; * non si riesce a chiudere l'oggetto zip;
References QuaZip::close(), QuaZip::getZipError(), QuaZip::mdCreate, and QuaZip::open().
QString JlCompress::extractFile (QString fileCompressed, QString fileName, QString fileDest = QString()) [static]
OK Estrae il file fileName, contenuto nel file fileCompressed, con il nome fileDest. Se fileDest = `` allora il file viene estratto con lo stesso nome con cui è stato compresso. Se la funzione fallisce cancella il file che si è tentato di estrarre. Restituisce il nome assoluto del file estratto.
La funzione fallisce se: * non si riesce ad aprire l'oggetto zip; * l'estrazione del file fallisce; * non si riesce a chiudere l'oggetto zip;
References QuaZip::close(), QuaZip::getZipError(), QuaZip::mdUnzip, and QuaZip::open().
QStringList JlCompress::extractFiles (QString fileCompressed, QStringList files, QString dir = QString()) [static]
OK Estrae i file specificati in files, contenuti nel file fileCompressed, nella cartella dir. La struttura a cartelle del file compresso viene rispettata. Se dir = `` allora il file viene estratto nella cartella corrente. Se la funzione fallisce cancella i file che si è tentato di estrarre. Restituisce i nomi assoluti dei file estratti.
La funzione fallisce se: * non si riesce ad aprire l'oggetto zip; * l'estrazione di un file fallisce; * non si riesce a chiudere l'oggetto zip;
References QuaZip::close(), QuaZip::getZipError(), QuaZip::mdUnzip, and QuaZip::open().
QStringList JlCompress::extractDir (QString fileCompressed, QString dir = QString()) [static]
OK Estrae il file fileCompressed nella cartella dir. Se dir = `` allora il file viene estratto nella cartella corrente. Se la funzione fallisce cancella i file che si è tentato di estrarre. Restituisce i nomi assoluti dei file estratti.
La funzione fallisce se: * non si riesce ad aprire l'oggetto zip; * la compressione di un file fallisce; * non si riesce a chiudere l'oggetto zip;
References QuaZip::close(), getFileList(), QuaZip::getZipError(), QuaZip::mdUnzip, and QuaZip::open().
QStringList JlCompress::getFileList (QString fileCompressed) [static]
OK Restituisce la lista dei file resenti nel file compresso fileCompressed. Se la funzione fallisce, restituisce un elenco vuoto.
La funzione fallisce se: * non si riesce ad aprire l'oggetto zip; * la richiesta di informazioni di un file fallisce; * non si riesce a chiudere l'oggetto zip;
References QuaZip::close(), QuaZip::getCurrentFileInfo(), QuaZip::getZipError(), QuaZip::goToFirstFile(), QuaZip::goToNextFile(), QuaZip::mdUnzip, QuaZipFileInfo::name, and QuaZip::open().
Referenced by extractDir().
The documentation for this class was generated from the following files:
quazip/JlCompress.h
quazip/JlCompress.cpp